<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>varsel</artifactId>
		<groupId>no.nav.varsel</groupId>
		<version>5.4.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>varsel-jms-producer</artifactId>
	<name>Varsel :: JMS Producer</name>

	<dependencies>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-jms</artifactId>
		</dependency>

		<!--provided-->
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec.javax.jms</groupId>
			<artifactId>jboss-jms-api_2.0_spec</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.activation</groupId>
			<artifactId>javax.activation</artifactId>
		</dependency>

		<!-- test -->
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-config</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


</project>