# automatic fasit properties
node.hostname=e34jbsl01591.devillo.no
applicationName=varsel

# spring context path
server.contextPath=/varsel

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.generate-ddl=true
spring.batch.initializer.enabled=true

spring.jta.atomikos.datasource.min-pool-size=10
spring.jta.atomikos.datasource.max-pool-size=50

# div env/spring props
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# LDAP
ldap.url=ldap\://ldapgw.test.local
ldap.basedn=dc\=test,dc\=local
ldap.username=local
ldap.***passord=gammelt_passord***
ldap.domain=TEST.LOCAL
ldap.serviceuser.basedn=ou\=ServiceAccounts,dc\=test,dc\=local
ldap.user.basedn=ou\=NAV,ou\=BusinessUnits,dc\=test,dc\=local

# Webservice
#dkif.ws.endpointUrl=https://app-t5.adeo.no/digital-kontaktinformasjon/DigitalKontaktinformasjon/v1
#aktoerv2.ws.endpointUrl=https://service-gw-t5.test.local/

# Fasit varselProps

varsel.jms.consumer.error.enable.automatic.shutdown=true
# Number of errors needed to stop a consumer
varsel.jms.consumer.error.context.size=20
# Number of seconds the "number of errors" defined in context.size needs to be within to stop a consumer
varsel.jms.consumer.error.context.time.seconds=600
# Number of seconds to wait before restarting consumer
varsel.jms.consumer.error.restart.delay.seconds=600

varsel.jms.consumer.min=1
varsel.jms.consumer.max=2

varsel.url=http://nav.no/varsel/{id}