# enables jboss profile
spring.profiles.active=remote

# Don't print the application banner when starting
spring.main.show_banner=false

applicationVersion=${project.version}
bootstrapVersion=${bootstrap.version}
