# automatic fasit properties
node.hostname=e34jbsl01591.devillo.no
applicationName=varsel

# spring context path
server.contextPath=/varsel


# div env/spring props
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
