server.servlet.context-path=/varsel
applicationName=varsel
spring.jpa.open-in-view=false

# Don't print the application banner when starting
spring.main.banner-mode=OFF

# Disable batch auto-start
spring.batch.job.enabled=false

applicationVersion=@project.version@
bootstrapVersion=@bootstrap.version@

spring.jpa.properties.hibernate.ejb.interceptor=no.nav.varsel.domain.auxiliary.ChangeStampInterceptor
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent_output=true

varsel.admin.adrole=0000-GA-Varseladmin
varsel.jms.consumer.min=1
varsel.jms.consumer.max=2

# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

mqgateway01.autostart=true