# enables jboss profile
spring.profiles.active=remote

# Don't print the application banner when starting
spring.main.show_banner=false

applicationVersion=${project.version}
bootstrapVersion=${bootstrap.version}

spring.jpa.properties.hibernate.ejb.interceptor=no.nav.varsel.domain.auxiliary.ChangeStampInterceptor
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent_output=true