server.port=8041

spring.profiles.include=local

# Webservice
dkif.ws.url=http://localhost:8041/varsel/ws/DigitalKontaktinformasjonV1
aktoerv2.ws.url=http://localhost:8041/varsel/ws/AktoerV2

# Rest
dokkat.varselinfo.rest.url=http://localhost:8041/varsel/rest/varselInfoV1