<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>varsel</artifactId>
		<groupId>no.nav.varsel</groupId>
		<version>1-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>app</artifactId>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>tvarsel005</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>jms-consumer</artifactId>
		</dependency>

		<dependency>
			<groupId>io.dropwizard.metrics</groupId>
			<artifactId>metrics-servlets</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>

		<!--modig-->
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-log-filter</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-filter</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-core</artifactId>
		</dependency>

		<dependency>
			<groupId>no.nav.security</groupId>
			<artifactId>token-validation-spring</artifactId>
		</dependency>

		<!-- test -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-wiremock</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>config</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>repo</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>jms</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>ws-consumer</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jta-atomikos</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>kvarsel001</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<finalName>app</finalName>
					<mainClass>no.nav.varsel.Application</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>