<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>varsel</artifactId>
		<groupId>no.nav.varsel</groupId>
		<version>4.0.5</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>varsel-ws-provider</artifactId>
	<name>Varsel :: WebService Provider</name>

	<dependencies>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-ws</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-service</artifactId>
		</dependency>

		<!-- modig -->
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-log-filter</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-log-jaxws</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-ws</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-loginmodule</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-authorization</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester</groupId>
			<artifactId>nav-brukervarsel-v1-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>

		<!--provided-->
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec.javax.jms</groupId>
			<artifactId>jboss-jms-api_2.0_spec</artifactId>
			<scope>provided</scope>
		</dependency>

		<!--test-->
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-config</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-repo</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-jms</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-ws-consumer</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-core</artifactId>
			<classifier>tests</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-testcertificates</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


</project>