INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SMS', 'SMS Melding', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('EPOST', 'E-post', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('DITTNAV', 'Ditt Nav', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');

INSERT INTO K_STATUS (K_STATUS, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('OPPRETTET', 'Opprettet', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_STATUS (K_STATUS, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SENDT', 'Sendt', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_STATUS (K_STATUS, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('FERDIGBEHANDLET', 'Ferdigbehandlet', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_STATUS (K_STATUS, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('FEILET', 'Feilet', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');