DROP SEQUENCE VARSELBESTILLING_SEQ;
CREATE SEQUENCE VARSELBESTILLING_SEQ START WITH 100000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
DROP SEQUENCE VARSEL_SEQ;
CREATE SEQUENCE VARSEL_SEQ START WITH 100000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;