<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>varsel</artifactId>
		<groupId>no.nav.varsel</groupId>
		<version>1.2.1-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>varsel-jms</artifactId>
	<name>Varsel :: JMS</name>

	<dependencies>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-domain</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jms</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-oxm</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec.javax.jms</groupId>
			<artifactId>jboss-jms-api_1.1_spec</artifactId>
		</dependency>

		<!--Tjenestespesifikasjoner-->
		<dependency>
			<groupId>no.nav.meldinger.virksomhet</groupId>
			<artifactId>nav-virksomhet-varsel-v1-meldingsdefinisjon</artifactId>
			<classifier>jaxb</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.meldinger.virksomhet</groupId>
			<artifactId>nav-virksomhet-varselutsending-v2-meldingsdefinisjon</artifactId>
			<classifier>jaxb</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.meldinger.virksomhet</groupId>
			<artifactId>nav-virksomhet-varselKvittering-v1-meldingsdefinisjon</artifactId>
			<classifier>jaxb</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.meldinger.virksomhet</groupId>
			<artifactId>nav-virksomhet-varselMedHandling-v1-meldingsdefinisjon</artifactId>
			<classifier>jaxb</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.meldinger.virksomhet</groupId>
			<artifactId>nav-virksomhet-stoppReVarsel-v1-meldingsdefinisjon</artifactId>
			<classifier>jaxb</classifier>
		</dependency>

		<dependency>
			<groupId>com.ryantenney.metrics</groupId>
			<artifactId>metrics-spring</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
		</dependency>

		<!-- test -->
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-config</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>