CREATE TABLE VARSELBESTILLING (
  ID                       NUMBER(19, 0)     NOT NULL,
  VARSELBESTILLING_ID      VARCHAR2(40 CHAR) NOT NULL,
  VARSLINGSTYPE            VARCHAR2(50 CHAR) NOT NULL,
  PREFERERT_KANAL          VARCHAR2(50 CHAR),
  UTLOP_TIDSPUNKT          TIMESTAMP,
  FNR                      VARCHAR2(20 CHAR) NOT NULL,
  AKTOR_ID                 VARCHAR2(50 CHAR) NOT NULL,
  BESTILLINGS_TIDSPUNKT    TIMESTAMP         NOT NULL,
  REVARSLING_INTERVALL     NUMBER(10, 0),
  ANTALL_REVARSLINGER      NUMBER(10, 0),
  NESTE_VARSLING_TIDSPUNKT TIMESTAMP,
  OPPRETTET_AV             VARCHAR2(50 CHAR) NOT NULL,
  OPPRETTET_DATO           TIMESTAMP         NOT NULL,
  ENDRET_AV                VARCHAR2(50 CHAR),
  ENDRET_DATO              TIMESTAMP,
  VERSJON                  NUMBER(19, 0)     NOT NULL,
  CONSTRAINT XPK_VARSELBEST PRIMARY KEY (ID)
);

CREATE TABLE VARSEL (
  ID                     NUMBER(19, 0)       NOT NULL,
  VARSEL_ID              VARCHAR2(40 CHAR)   NOT NULL,
  K_KANAL                VARCHAR2(50 CHAR)   NOT NULL,
  SENDT_TIDSPUNKT        TIMESTAMP,
  DISTRIBUSJON_TIDSPUNKT TIMESTAMP,
  KONTAKT_INFO           VARCHAR2(255 CHAR)  NOT NULL,
  K_STATUS               VARCHAR2(50 CHAR)   NOT NULL,
  FEILBESKRIVELSE        VARCHAR2(1000 CHAR),
  VARSEL_TITTEL          VARCHAR2(255 CHAR),
  VARSEL_TEKST           VARCHAR2(1000 CHAR) NOT NULL,
  VARSEL_URL             VARCHAR2(255 CHAR),
  FK_VARSELBESTILLING_ID NUMBER(19, 0)       NOT NULL,
  OPPRETTET_AV           VARCHAR2(50 CHAR)   NOT NULL,
  OPPRETTET_DATO         TIMESTAMP           NOT NULL,
  ENDRET_AV              VARCHAR2(50 CHAR),
  ENDRET_DATO            TIMESTAMP,
  VERSJON                NUMBER(19, 0)       NOT NULL,
  CONSTRAINT XPK_VARSEL PRIMARY KEY (ID)
);

CREATE TABLE PARAMETER (
  FK_VARSELBESTILLING_ID NUMBER(19, 0)      NOT NULL,
  KEY                    VARCHAR2(255 CHAR) NOT NULL,
  VALUE                  VARCHAR2(255 CHAR) NOT NULL,
  CONSTRAINT xpk_parameter PRIMARY KEY (FK_VARSELBESTILLING_ID, KEY)
);

CREATE TABLE K_KANAL (
  K_KANAL        VARCHAR2(20 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_KANAL PRIMARY KEY (K_KANAL)
);

CREATE TABLE K_STATUS (
  K_STATUS       VARCHAR2(20 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_STATUS PRIMARY KEY (K_STATUS)
);

ALTER TABLE VARSEL
  ADD CONSTRAINT FK_VARS_VARSBEST
FOREIGN KEY (FK_VARSELBESTILLING_ID)
REFERENCES VARSELBESTILLING;

ALTER TABLE VARSEL
  ADD CONSTRAINT FK_VARS_KANAL
FOREIGN KEY (K_KANAL)
REFERENCES K_KANAL;

ALTER TABLE VARSEL
  ADD CONSTRAINT FK_VARS_STATUS
FOREIGN KEY (K_STATUS)
REFERENCES K_STATUS;

CREATE UNIQUE INDEX VARSEL_VARSEL_ID ON VARSEL (VARSEL_ID);
CREATE UNIQUE INDEX VARSELBEST_VARSEL_ID ON VARSELBESTILLING (VARSELBESTILLING_ID);

CREATE SEQUENCE VARSELBESTILLING_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE VARSEL_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
