ALTER TABLE VARSELBESTILLING
  MODIFY NESTE_VARSLING_TIDSPUNKT DATE;

ALTER TABLE VARSELBESTILLING
  DROP COLUMN PREFERERT_KANAL;

CREATE TABLE VARSELBEST_PREFKANAL (
  FK_VARSELBESTILLING_ID NUMBER(19, 0)     NOT NULL,
  K_KANAL                  VARCHAR2(20 CHAR) NOT NULL,
  CONSTRAINT xpk_prefkanal PRIMARY KEY (FK_VARSELBESTILLING_ID, K_KANAL)
);

ALTER TABLE VARSELBEST_PREFKANAL
  ADD CONSTRAINT FK_VARSBESTKAN_VARSBEST
FOREIGN KEY (FK_VARSELBESTILLING_ID)
REFERENCES VARSELBESTILLING;

ALTER TABLE VARSELBEST_PREFKANAL
  ADD CONSTRAINT FK_VARSBEST_KANAL
FOREIGN KEY (K_KANAL)
REFERENCES K_KANAL;
