ALTER TABLE VARSELBESTILLING
  DROP COLUMN NESTE_VARSLING_TIDSPUNKT;

ALTER TABLE VARSELBESTILLING
  ADD NESTE_VARSLING_DATO DATE;

drop TABLE VARSELBEST_PREFKANAL;

ALTER TABLE VARSELBESTILLING
  ADD VARSELTYPE_ID VARCHAR2(50 CHAR);

UPDATE VARSELBESTILLING
SET VARSELTYPE_ID = VARSLINGSTYPE;

ALTER TABLE VARSELBESTILLING
  MODIFY VARSELTYPE_ID NOT NULL;

ALTER TABLE VARSELBESTILLING
  DROP COLUMN VARSLINGSTYPE;
