-- DITTNAV is renamed to DITT_NAV

INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('DITT_NAV', 'Ditt Nav', 'Gerhard Wiese', TIMESTAMP '2016-06-08 10:00:00');

UPDATE VARSEL
SET K_KANAL = 'DITT_NAV'
WHERE K_KANAL = 'DITTNAV';

UPDATE VARSELBEST_PREFKANAL
SET K_KANAL = 'DITT_NAV'
WHERE K_KANAL = 'DITTNAV';

DELETE FROM K_KANAL
WHERE K_KANAL = 'DITTNAV';
