<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>varsel</artifactId>
		<groupId>no.nav.varsel</groupId>
		<version>1-SNAPSHOT</version>
	</parent>

	<artifactId>varsel-jms-consumer</artifactId>
	<name>Varsel :: JMS Consumer</name>

	<dependencies>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-jms</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-service</artifactId>
		</dependency>

		<!-- test -->
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-config</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-repo</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-jms</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-service</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.varsel</groupId>
			<artifactId>varsel-ws-consumer</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-testcertificates</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.awaitility</groupId>
			<artifactId>awaitility</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-wiremock</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jta-atomikos</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


</project>