kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  kafka:
    pool: {{ KAFKA_POOL }}
  env:
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: VARSEL_ENDPOINTS_DIGDIR_KRR_PROXY_URL
      value: {{ VARSEL_ENDPOINTS_DIGDIR_KRR_PROXY_URL }}
    - name: VARSEL_ENDPOINTS_DIGDIR_KRR_PROXY_SCOPE
      value: {{ VARSEL_ENDPOINTS_DIGDIR_KRR_PROXY_SCOPE }}
    - name: VARSEL_ENDPOINTS_DOKMET_URL
      value: {{ VARSEL_ENDPOINTS_DOKMET_URL }}
    - name: VARSEL_ENDPOINTS_PDL_URL
      value: {{ VARSEL_ENDPOINTS_PDL_URL }}
    - name: VARSEL_ENDPOINTS_PDL_SCOPE
      value: {{ VARSEL_ENDPOINTS_PDL_SCOPE }}
    - name: VARSEL_SIGSUBJECTCERTCONSTRAINTS
      value: {{ VARSEL_SIGSUBJECTCERTCONSTRAINTS }}
    - name: VARSEL_QUEUES_BESTILLSERVICEMELDING_QUEUENAME
      value: {{ VARSEL_QUEUES_BESTILLSERVICEMELDING_QUEUENAME }}
    - name: VARSEL_QUEUES_BESTILLSERVICEMELDING_FUNKFEILQUEUENAME
      value: {{ VARSEL_QUEUES_BESTILLSERVICEMELDING_FUNKFEILQUEUENAME }}
    - name: VARSEL_URL
      value: {{ VARSEL_URL }}
    - name: VARSEL_JMS_CONSUMER_ERROR_CONTEXT_SIZE
      value: "{{ VARSEL_JMS_CONSUMER_ERROR_CONTEXT_SIZE }}"
    - name: VARSEL_JMS_CONSUMER_ERROR_CONTEXT_TIME_SECONDS
      value: "{{ VARSEL_JMS_CONSUMER_ERROR_CONTEXT_TIME_SECONDS }}"
    - name: VARSEL_JMS_CONSUMER_ERROR_RESTART_DELAY_SECONDS
      value: "{{ VARSEL_JMS_CONSUMER_ERROR_RESTART_DELAY_SECONDS }}"
    - name: LISTENER_AUTO_STARTUP
      value: "{{ LISTENER_AUTO_STARTUP }}"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{ this }}
           {{/each}}
  liveness:
    path: /varsel/actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /varsel/actuator/prometheus
  readiness:
    path: /varsel/actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 3072Mi
    requests:
      memory: 1920Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ DB_CREDS }}
        mountPath: "/var/run/secrets/nais.io/db_creds"
      - kvPath: {{ DB_CONFIG }}
        mountPath: "/var/run/secrets/nais.io/db_config"
      - kvPath: {{ SERVICEUSER_VAULT_PATH }}
        mountPath: /secrets/serviceuser/srvvarsel
  azure:
    application:
      enabled: true
  webproxy: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
