kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{ this }}
           {{/each}}
  liveness:
    path: varsel/isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: varsel/isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 3072Mi
    requests:
      memory: 1920Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ VARSEL_DS }}
        mountPath: /var/run/secrets/nais.io/varselDS