server.port=8041

spring.main.allow-bean-definition-overriding=true
varsel.serviceuser.username=itestuser
varsel.serviceuser.password=itestpw

# sts
securitytokenservice.url=http://dummy

# Webservice
dkif.ws.endpointUrl=http://localhost:8041/varsel/ws/DigitalKontaktinformasjonV1

varsel_sigsubjectcertconstraints=.*DC=test.*DC=local,.*test.local.*,.*DC=preprod.*DC=local,.*preprod.local.*

dokkat.varselinfo.rest.url=http://localhost:${wiremock.server.port}/varsel/rest/varselInfoV1
security.token.rest.service.url=http://localhost:${wiremock.server.port}/securitytoken
pdl.url=http://localhost:${wiremock.server.port}/pdl

bestillservicemelding.queuename=mq_bestillServicemelding
varselutsending.queuename=mq_varselutsending
bestillservicemeldingkontaktinfo.queuename=mq_revarselStopp
mqgateway01.hostname=activemq
mqgateway01.port=0
mqgateway01.name=activemq
varselchannel.name=varsel_channel

wiremock.reset-mappings-after-each-test=true
listener.autoStartup=true