server.servlet.context-path=/varsel
applicationName=varsel
spring.jpa.open-in-view=false
server.shutdown=graceful
spring.main.banner-mode=OFF

# Disable batch auto-start
spring.batch.job.enabled=false

spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.varsel.domain.auxiliary.ChangeStampInterceptor
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent_output=true

varsel.admin.adrole=0000-GA-Varseladmin
varsel.jms.consumer.min=1
varsel.jms.consumer.max=2

# actuators
management.endpoints.web.exposure.include=prometheus,health
# actuator - health
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.group.liveness.include=jms

# actuator - metrics
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.enable.http.client.requests=false

# kafka
spring.kafka.bootstrap-servers=${KAFKA_BROKERS}
spring.kafka.security.protocol=SSL

spring.kafka.ssl.trust-store-type=JKS
spring.kafka.ssl.trust-store-location=file:${KAFKA_TRUSTSTORE_PATH}
spring.kafka.ssl.trust-store-password=${KAFKA_CREDSTORE_PASSWORD}

spring.kafka.ssl.key-store-type=PKCS12
spring.kafka.ssl.key-store-location=file:${KAFKA_KEYSTORE_PATH}
spring.kafka.ssl.key-store-password=${KAFKA_CREDSTORE_PASSWORD}
spring.kafka.ssl.key-password=${KAFKA_CREDSTORE_PASSWORD}

# kafka confluent
spring.kafka.properties.schema.registry.url=${KAFKA_SCHEMA_REGISTRY}
spring.kafka.properties.basic.auth.credentials.source=USER_INFO
spring.kafka.properties.basic.auth.user.info=${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}

# Kafka producer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.retries=2
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

privat-dok-notifikasjon-med-kontakt-info.topic=teamdokumenthandtering.privat-dok-notifikasjon-med-kontakt-info
privat-dok-notifikasjon.topic=teamdokumenthandtering.privat-dok-notifikasjon
brukernotifikasjon.beskjed.topic=min-side.aapen-brukernotifikasjon-beskjed-v1

# Kafka consumer
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.properties.enable.auto.commit=false
spring.kafka.consumer.properties.retry.backoff.ms=2000
spring.kafka.consumer.properties.reconnect.backoff.ms=2000
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=record
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer