server.port=8041
spring.main.allow-bean-definition-overriding=true
varsel.serviceuser.username=itestuser
varsel.serviceuser.password=itestpw
# sts
securitytokenservice.url=http://dummy
# Webservice
digdir_krr_proxy_url=http://localhost:8041/DIGDIR_KRR_PROXY
varsel_sigsubjectcertconstraints=.*DC=test.*DC=local,.*test.local.*,.*DC=preprod.*DC=local,.*preprod.local.*
dokmet.varselinfo.url=http://localhost:${wiremock.server.port}/varsel/rest/varselInfoV1
security.token.rest.service.url=http://localhost:${wiremock.server.port}/securitytoken
pdl.url=http://localhost:${wiremock.server.port}/pdl
bestillservicemelding.queuename=mq_bestillServicemelding
bestillservicemelding.funkfeil.queuename=mq_bestillServicemelding_funkfeil
varselutsending.queuename=mq_varselutsending
bestillservicemeldingkontaktinfo.queuename=mq_revarselStopp
bestillservicemeldingkontaktinfo.funkfeil.queuename=mq_revarselStopp_funkfeil
mqgateway01.hostname=activemq
mqgateway01.port=0
mqgateway01.name=activemq
mqgateway01.channel.name=varsel_channel
mqgateway01.channel.securename=activemq
mqgateway01.channel.enabletls=true
wiremock.reset-mappings-after-each-test=true
listener.autoStartup=true
azure.openid-config-token-endpoint=http://localhost:${wiremock.server.port}/azure_token
azure.app-client-id=azureClientId
azure.app-client-secret=azureClientSecret
azure.app-scope.digdir.krr=varsel2
